name: Matrix

on: push

jobs:
  runs-on: ubuntu-latest
  node-version:
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with: 
          node-verison: 6
      - name: Log node version
        run: node -v

                          
              
            